# Site settings
title: Associação Filarmónica Serpinense
header: Bem vindo
mobile: 91 940 76 16
email: filarmonicaserpinense@gmail.com 
url: http//filarmonicaserpinense.com
description: "A Associação Filarmónica Serpinense é uma Associação jovem, fundada em 1995, com sede em Serpins, uma Vila no concelho da Lousã, no Centro de Portugal."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Associação Filarmónica Serpinense

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/afserpinense

# Build settings
markdown: kramdown
permalink: pretty
